eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8112
spring:
  application:
    name: api-test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddo?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  #redis
  #database name
  redis:
    # Redis 服务器地址
    host: 127.0.0.1
    # Redis 服务器连接端口
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password:
    # Redis 数据库索引（默认为0）
    database: 1
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
  cloud:
    refresh:
      refreshable: none
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
app:
  filePath: c:/var/uploaded_files/
  pre: /files
author:
  name: wyh
  age: 30
DEST: D:\CFCA\test.pdf
HTML: freemarker.ftl
FONT: simhei.ttf